### ISSUE TITLE
Compile error for using bincode::Error on 1.7.1

### ISSUE THREAD

**Issue by Leo1003** [lovasoa/custom_error#21]
After upgrading to 1.7.1, the compiler complained that `error[E0277]: the trait bound 'std::boxed::Box<bincode::ErrorKind>: std::borrow::Borrow<dyn std::error::Error>' is not satisfied`

I'm sure that it didn't occurred on `1.6.0` and `1.7.0`. But this version breaks my codes... 
Note: The `bincode::ErrorKind` enum DO implement `std::error::Error`.

---
Details: 
```text
error[E0277]: the trait bound `std::boxed::Box<bincode::ErrorKind>: std::borrow::Borrow<dyn std::error::Error>` is not satisfied

custom_error! {pub SimpleError
    Binary { source: bincode::Error } = "Binary Serialize/Deserialize Error",
}
= help: the following implementations were found:
             <std::boxed::Box<T> as std::borrow::Borrow<T>>
   = note: required by `std::borrow::Borrow::borrow`
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
```

**Comment by Leo1003** [comment]
- `std::boxed::Box` do implement `std::borrow::Borrow`
- `bincode::ErrorKind` do implement `std::error::Error`

This would fail to compile: 
```rust
let a: &dyn std::error::Error = std::borrow::Borrow::borrow(&e);
```

```
39 | let a: &dyn std::error::Error = std::borrow::Borrow::borrow(&e);
   |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `std::borrow::Borrow<dyn std::error::Error>` is not implemented for `std::boxed::Box<bincode::ErrorKind>`
```

But this is ok: 

```rust
let a: &bincode::ErrorKind = std::borrow::Borrow::borrow(&e);
let b: &dyn std::error::Error = a;
```
:frowning:

**Comment by lovasoa** [comment]
yes. But the thing is: the macro cannot generate the second code, because it does not have access to the underlying type (bincode::ErrorKind).

**Comment by lovasoa** [comment]
If this is in fact possible and you have an idea of how to implement the conversion that works for both Box<dyn Error> and Box<ConcreteErrorType>, let me know!

**Comment by lovasoa** [comment]
If this is in fact possible and you have an idea of how to implement the conversion that works for both Box<dyn Error> and Box<ConcreteErrorType>, let me know!

**Comment by Leo1003** [comment]
This is the most possible solution I could find...
I don't know if this can be generated by macro.

```rust
let a: &dyn std::error::Error = std::borrow::Borrow::borrow(&*e);
```

I am sorry that I may not provide more help because I am not familiar with macro...

**Comment by lovasoa** [comment]
The problem is that `&*e` doesn't work for non-boxed errors.

**Comment by glehmann** [comment]
Is there a known workaround for this problem?
Should we file a bug report at bincode?

**Comment by lovasoa** [comment]
The workaround is to manually implement `From<bincode::Error>` for your error, and to name the field something other than `source`...

You can open a bug report at bincode, as it is indeed unconventional not to implement `std::error::Error` on your main error type, but since it essentially just works in every other case, I'm not sure they'll be willing to do something...

**Comment by glehmann** [comment]
Thanks! I'll file a bug report tomorrow.

**Comment by glehmann** [comment]
I guess https://github.com/servo/bincode/issues/227 is related — would it be good enough for custom_error?

**Comment by lovasoa** [comment]
Yes, it's exactly what we would need!

**Comment by ZoeyR** [comment]
Hi, maintainer of bincode here. `Error` should be implemented for all `Box<T> where T: Error` by a blanket impl in std. I'm not sure what bincode could do to fix this.

**Comment by lovasoa** [comment]
An error type has to implement `std::borrow::Borrow<dyn std::error::Error>` for it to work with custom_error. This allows the library to implement [`source`](https://doc.rust-lang.org/std/error/trait.Error.html#method.source) for both types that implement `Error` directly and `Box<dyn Error>`. Unfortunately, this does not for other boxed error types.

**Comment by kkharji** [comment]
I'm having similar issue:

error: `the trait bound tree_sitter::LanguageError: StdError is not satisfied required for the cast to the object type dyn StdError`

LanguageError definition:

```rust
/// An error that occurred when trying to assign an incompatible `Language` to a `Parser`.
#[derive(Debug, PartialEq, Eq)]
pub struct LanguageError {
    version: usize,
}

```

My definition:

```rust
custom_error! {
    pub Error
    ParseError = "Unable to create tree_sitter tree.",
    Io{source: io::Error}         = "unable to read from the file",
    LangError{source: LanguageError} = "Unable to load language tree_sitter v{source}"

}

```

Thanks 

cc @Leo1003

**Comment by lovasoa** [comment]
[`tree_sitter::LanguageError`](https://docs.rs/tree-sitter/0.19.3/tree_sitter/struct.LanguageError.html) does not implement the standard [Error](https://doc.rust-lang.org/std/error/trait.Error.html) trait. You should open an issue on their side.
